---

- name: Ensure for backup user is exists
  user: name={{backup_user}}

- name: Ensure for backup directories is exits
  file: path={{item}} state=directory owner={{backup_user}}
  with_items:
    - "{{backup_home}}"
    - "{{backup_work}}"
    - "{{backup_logdir}}"

- name: Install duply
  copy: src=duply dest={{backup_home}}/duply owner={{backup_user}} mode=0755

- name: Prepare backup profiles - pt. 1
  file: path={{backup_home}}/{{item.name}} state=directory mode=0700 owner={{item.user|default(backup_user)}} 
  with_items: backups

- name: Prepare backup profiles - pt. 2
  template: src=conf.j2 dest={{backup_home}}/{{item.name}}/conf owner={{item.user|default(backup_user)}}
  with_items: backups

- name: Prepare backup profiles - pt. 3
  template: src=exclude.j2 dest={{backup_home}}/{{item.name}}/exclude owner={{item.user|default(backup_user)}} 
  with_items: backups

- name: Prepare backup profiles - pt. 4
  template: src=pre_{{item.source.split(':')[0]}}.j2 dest={{backup_home}}/{{item.name}}/pre owner={{item.user|default(backup_user)}} 
  when: item.source.find(':') != -1
  with_items: backups

- name: Prepare backup profiles - pt. 5
  template: src=post_{{item.source.split(':')[0]}}.j2 dest={{backup_home}}/{{item.name}}/post owner={{item.user|default(backup_user)}} 
  when: item.source.find(':') != -1
  with_items: backups

- name: Prepare backup profiles - pt. 6
  file: state=directory path={{backup_work}}/{{item.name}} owner={{item.user|default(backup_user)}} 
  with_items: backups

- name: Prepare backup profiles - pt. 7
  file: state=directory path={{backup_logdir}}/{{item.name}} owner={{item.user|default(backup_user)}} 
  with_items: backups

- name: Setup cron
  template: src=cron.j2 dest=/etc/cron.d/backup owner=root group=root mode=0644
